version: '3.8'

services:
  # Ollama AI 服务 - VPS 内存优化版
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_vps
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_KEEP_ALIVE=5m        # 5分钟后释放内存
      - OLLAMA_MAX_LOADED_MODELS=1  # 最多加载1个模型
      - OLLAMA_NUMA=false           # 禁用 NUMA
    deploy:
      resources:
        limits:
          memory: 3G                # 限制内存使用
        reservations:
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  # 瓦斯管理系统应用
  gas-app:
    build:
      context: .
      dockerfile: Dockerfile.vps
    container_name: gas_management_app
    ports:
      - "3000:3000"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  ollama_data:
    driver: local
